# Generated by Django 3.0.8 on 2020-07-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('twitch', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('guild_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('exp', models.IntegerField()),
                ('lvl', models.IntegerField()),
            ],
        ),
    ]
