# Generated by Django 3.0.8 on 2020-07-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200722_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
