# Generated by Django 3.0.8 on 2020-07-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='guild_id',
            new_name='disc_gid',
        ),
    ]
