# Generated by Django 3.0.8 on 2020-08-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200729_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lvl',
            field=models.IntegerField(default=0),
        ),
    ]
