# Generated by Django 3.0.8 on 2020-07-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddField(
            model_name='quote',
            name='character',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='episode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='series',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(),
        ),
    ]
